### ISSUE TITLE
Plugin allows users to specify hostname that does not conform to defined prefixes. 

### ISSUE THREAD

**Issue by gruffled** [vmware-archive/legacy-terraform-provider-vra7#79]
Hi, 

Our users have been able to use the plugin to create machines using hostnames of their choosing. This wouldn't be so bad but, we have defined hostname prefixes in `vRA > Infrastructure` > `Administration` > `Machine prefixes` that are required. 

Is this behaviour intended?

**Comment by hobovirtual** [comment]
I guess your users are using the Hostname property in their declaration which overrides the default Machine Prefix defined in your environment?

If that's the case, then the issue is not related to the provider itself, but rather just a normal behavior in vRA.

You can get more documentation on the property below (just a copy and paste from the official documentation)

**Property**: _Hostname_
**Definition**: _Specifies the host machine name, overriding the generated machine name contained in the VirtualMachine.Admin.Name property. If Hostname is not used, the VirtualMachine.Admin.Name value is used as the machine name. The maximum number of allowed characters for the Hostname value is 15._

As far as i know, i will let @vaficionado and @raghavav confirm, there's no way to prevent the use of properties via an API call.

**Comment by gruffled** [comment]
I thought that might be the case. Thank you.
